// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';


console.log("about to load");

var worker = new Worker("worker.bs.js");

var msg = {
  text: "Hello world"
};

worker.postMessage(msg);

function msgBackHandler(e) {
  console.log("I am the main thread and I have received a message back from the worker:");
  console.log(e.data);
  return /* () */0;
}

worker.onmessage = msgBackHandler;

console.log("Hello, BuckleScript and Reason!");

export {
  worker         ,
  msg            ,
  msgBackHandler ,
  
}
/*  Not a pure module */
